const contentEs = {
  addingNote: "Agregar una nota",
  editinNote: "Editar una nota",
  send: "Enviar",
  enterYourRequest: "Buscar por texto",
  enterText: "Ingrese texto ...",
  enterTextInput: "Ingrese texto ...",
  answer:"Respuesta",
  reply: "Respuesta",
  edit: "Editar",
  delete: "Borrar",
  yourAnswer: "Tu respuesta",
  editMessage: "Editar un mensaje",
  catcher: {
    tooManyRequest: "Demasiadas solicitudes. Intenta más tarde.",
    userNotAuthorized: "El usuario no está autorizado",
    unknownError: "Error desconocido",
  },
  errorTitle: "Error",
  errorText: "Error del servidor.Póngase en contacto con el soporte.",
  confirmation: "Confirmación",
  areYouSureYouWantToDelete:"Estas seguro que quieres borrarlo",
  note: "nota",
  message: "mensaje",
  confirm: "Confirmar",
  cancel: "Cancelar",
  answerT:"respuesta",
};

export default contentEs;
