const contentFr = {
  addingNote: "Ajouter une note",
  editinNote: "Modifier une note",
  send: "Envoyer",
  enterYourRequest: "Recherche par texte",
  enterText: "Entrez du texte ...",
  enterTextInput: "Entrez du texte ...",
  answer:"la réponse",
  reply: "Répondre",
  edit: "Modifier",
  delete: "Supprimer",
  yourAnswer: "Votre Réponse",
  editMessage: "Modifier un message",
  catcher: {
    tooManyRequest: "Trop de demandes. Essayer plus tard.",
    userNotAuthorized: "Utilisateur non autorisé",
    unknownError: "Erreur inconnue",
  },
  errorTitle: "Erreur",
  errorText: "Erreur de serveur. Veuillez contacter l'assistance.",
  confirmation: "Confirmation",
  areYouSureYouWantToDelete:"Etes-vous sûr que vous voulez supprimer",
  note: "note",
  message: "message",
  confirm: "Confirmer",
  cancel: "Annuler",
  answerT:"répondre",
}
export default contentFr;
