const contentEn = {
  addingNote: "Adding a note",
  editinNote: "Editing a note",
  send: "Send",
  enterYourRequest: "Search by text",
  enterText: "Enter text ...",
  enterTextInput: "Enter text ...",
  answer:"Answer",
  reply: "Reply",
  edit: "Edit",
  delete: "Delete",
  yourAnswer: "Your Answer",
  editMessage: "Editing a message",
  catcher: {
    tooManyRequest: "Too many requests. Try later.",
    userNotAuthorized: "User is not authorized",
    unknownError: "Unknown error",
  },
  errorTitle: "Error",
  errorText: "Server error. Please contact support",
  confirmation: "Confirmation",
  areYouSureYouWantToDelete:"Are you sure you want to delete",
  note: "note",
  message: "message",
  confirm: "Confirm",
  cancel: "Cancel",
  answerT:"answer",
};

export default contentEn;
